Add tests for book hw
Oleksandr-Tymoshenko/Online-Book-Store pull request #14
Opened 2023-12-02 16:58 UTC by Oleksandr-Tymoshenko

screenshots with the test coverage result

![image](https://github.com/Oleksandr-Tymoshenko/Online-Book-Store/assets/137907096/24b65d39-9dd3-4022-a845-069aa0250ea9)
![image](https://github.com/Oleksandr-Tymoshenko/Online-Book-Store/assets/137907096/8f12bdc3-8eb5-4f8c-a737-fdaf61afa0b8)
![image](https://github.com/Oleksandr-Tymoshenko/Online-Book-Store/assets/137907096/9ab75b18-6cf9-46cf-9e06-3a0cb0ebaf4e)

2023-12-03 12:06 UTC, don-bigdad approved these changes

2023-12-03 12:06 UTC, don-bigdad commented on src/main/java/book/store/onlinebookstore/service/impl/BookServiceImpl.java
>      public void deleteById(Long id) {
Maybe better use @Pozitive anotattion at controll level

2023-12-03 12:06 UTC, don-bigdad commented on src/test/java/book/store/onlinebookstore/book/BookControllerTest.java
> +
can use @AfterEach to clear db
and @BeforeEach to set new values

2023-12-03 12:06 UTC, don-bigdad commented on src/test/java/book/store/onlinebookstore/book/BookControllerTest.java
> +        book1.setCategoriesIds(Set.of());
i prefer use private method to get default value of test entity and just call him in test

2023-12-03 12:06 UTC, don-bigdad commented on src/test/java/book/store/onlinebookstore/book/BookRepositoryTest.java
> +    @Sql(scripts = "classpath:database.scripts/book/clear-book-table.sql",
same,AfterEach clear db

2023-12-12 07:53 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution! 
please check all places to fix comments

2023-12-12 07:53 UTC, Elena-Bruyako commented on src/test/java/book/store/onlinebookstore/book/BookControllerTest.java
> +    @Sql(scripts = "classpath:database.scripts/book/clear-book-table.sql",
Let's use script in class level. Check other test methods to avoid duplicating

2023-12-12 07:53 UTC, Elena-Bruyako commented on src/test/java/book/store/onlinebookstore/book/BookControllerTest.java
> +        BookDto[] actual = objectMapper.readValue(result.getResponse().getContentAsString(),
You can use 
```
List<BookDto> actual = objectMapper.readValue(result.getResponse().getContentAsString(),
                new TypeReference<>() {});
```

to get List of BookDto

2023-12-12 07:53 UTC, Elena-Bruyako commented on src/test/java/book/store/onlinebookstore/book/BookControllerTest.java
> +        Assertions.assertEquals(expected.size(), actual.length);
it's good practice to use static import 
```suggestion
      assertEquals(expected.size(), actual.length);
```

2023-12-12 07:53 UTC, Elena-Bruyako commented on src/test/java/book/store/onlinebookstore/book/BookServiceTest.java
> +        Mockito.when(bookMapper.toBook(requestDto)).thenReturn(book);
```suggestion
        when(bookMapper.toBook(requestDto)).thenReturn(book);

```

Check all static imports

2023-12-12 07:53 UTC, Elena-Bruyako commented on src/test/java/book/store/onlinebookstore/book/BookRepositoryTest.java
> +    @Sql(scripts = "classpath:database.scripts/book/add-one-book.sql",
replace to class level

2023-12-12 07:53 UTC, Elena-Bruyako commented on src/test/java/book/store/onlinebookstore/book/BookServiceTest.java
> +        Assertions.assertThat(actual).isEqualTo(expected);
why not `assertEquals(expected, actual);` ?

2023-12-18 14:43 UTC, Elena-Bruyako approved these changes
Good job!

2023-12-20 12:13 UTC, merged