added global exception handler
Oleksandr-Tymoshenko/Online-Book-Store pull request #4
Opened 2023-10-16 17:57 UTC by Oleksandr-Tymoshenko

2023-10-17 16:11 UTC, mmosii approved these changes
Great job!

2023-10-19 00:20 UTC, NazarSmith228 requested changes
Good job! Let's improve your solution

2023-10-19 00:20 UTC, NazarSmith228 commented on pom.xml
> +        </dependency>
it is better to use `spring-boot-starter-validation`

2023-10-19 00:20 UTC, NazarSmith228 commented on src/main/java/book/store/onlinebookstore/controller/BookController.java
> +    public BookDto updateById(@PathVariable Long id,
just FYI

you may also validate such things as @PathVariable, @RequestParams etc. It looks like:
```
@PathVariable @Positive Long id
```

In order to be able to perform such validation you need to annotate your controller class with @Validated annotation

again, this is just FYI - apply it or not :)

2023-10-19 00:20 UTC, NazarSmith228 commented on src/main/java/book/store/onlinebookstore/dto/BookDto.java
> +                      BigDecimal price, String description, String coverImage) {
usually fields of records are formatted as follows:
```
public record BookDto(Long id, 
                      String title, 
                      String author, 
                      String isbn,
                      BigDecimal price, 
                      String description, 
                      String coverImage) {
```

2023-10-19 00:20 UTC, NazarSmith228 commented on src/main/java/book/store/onlinebookstore/dto/CreateBookRequestDto.java
> +        @NotNull @Min(0) BigDecimal price,
is it really necessary to use `@Min(0)`?

could you use `@Positive`?

2023-10-19 00:20 UTC, NazarSmith228 commented on src/main/java/book/store/onlinebookstore/dto/CreateBookRequestDto.java
> +        @NotNull String author,
it is better to use `@NotBlank` with strings

2023-10-19 00:20 UTC, NazarSmith228 commented on src/main/java/book/store/onlinebookstore/exception/GlobalExceptionHandler.java
> +        body.put("status: ", HttpStatus.BAD_REQUEST);
time is pretty useless in response body - it does not bring any value to the client

status is obvious as well - no sense to have it in body

2023-10-19 00:20 UTC, NazarSmith228 commented on src/main/java/book/store/onlinebookstore/exception/GlobalExceptionHandler.java
> +    protected ResponseEntity<Object> handleMethodArgumentNotValid(
do you have any other exceptions except for `MethodArgumentNotValidException`?

does it make sense to handle them as well?

2023-10-19 12:29 UTC, Oleksandr-Tymoshenko commented on src/main/java/book/store/onlinebookstore/controller/BookController.java
> +    public BookDto updateById(@PathVariable Long id,
I`ve added it in the next task

2023-10-20 13:39 UTC, NazarSmith228 requested changes
Good job! Just a few remarks left

2023-10-20 13:39 UTC, NazarSmith228 commented on src/main/java/book/store/onlinebookstore/exception/GlobalExceptionHandler.java
> +    }
it is a bad idea :)

better to handle specific exceptions

you can remove this handler

2023-10-20 13:39 UTC, NazarSmith228 commented on src/main/java/book/store/onlinebookstore/exception/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(ex.getMessage(), HttpStatus.INTERNAL_SERVER_ERROR);
```suggestion
    public ResponseEntity<String> handleEntityNotFound(EntityNotFoundException ex) {
        return new ResponseEntity<>(ex.getMessage(), HttpStatus.NOT_FOUND);

```

2023-10-21 15:56 UTC, NazarSmith228 approved these changes
LGTM

2023-10-23 11:16 UTC, merged